### ISSUE TITLE
Replace module docs by readme

### ISSUE THREAD

**Issue by janhohenheim** [bash/fmtastic#7]
you can use `#![doc = include_str!("../readme.md")]`
https://github.com/bash/fmtastic/blob/7a035a0d91bc55d8434cc98329dacd91ddaa4fe1/src/lib.rs#L1

**Comment by tautropfli** [comment]
I like the idea in theory, but I have some practical issues with it:
* My readme has things that don't belong in the crate docs: title with project name, build badges and licensing info.
* Links in crate docs should go to built docs, in the readme they go to docs.rs or docs.rust-lang.org.
* I like to hide imports in my rustdocs code examples but not necessarily in the readme.

I'm using a stub module so that my readme examples still get tested by `cargo test`:
```rust
#[doc = include_str!("../readme.md")]
mod doctest_readme {}
```
